// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFEcCavaRfYEOQzG4R0ZH2tqJKPD0EPRk',
    appId: '1:501064914725:web:298b98d200032d86482ccc',
    messagingSenderId: '501064914725',
    projectId: 'photos-app-e6687',
    authDomain: 'photos-app-e6687.firebaseapp.com',
    storageBucket: 'photos-app-e6687.appspot.com',
    measurementId: 'G-HMVW2BQ0W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxGfdICN4FDPx9-V38MfvDGWaJ7xe-TPk',
    appId: '1:501064914725:android:19fefc630f71b831482ccc',
    messagingSenderId: '501064914725',
    projectId: 'photos-app-e6687',
    storageBucket: 'photos-app-e6687.appspot.com',
  );
}
